# Site settings
title: The Wilke Lab
address: The University of Texas at Austin
email: wilke@austin.utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  The Wilke Lab carries out research in computational evolutionary biology,
  bioinformatics, and biostatistics.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ClausWilke
github_username:  wilkelab

# Collections
collections:
  classes:
    output: true
    permalink: /classes/:path/

# Build settings
markdown: kramdown
